### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#45]
Some form of sanitized logs will probably be useful for operating the server, at various severity levels.

**Comment by c633** [comment]
I propose to use [zap](https://github.com/uber-go/zap) since it has nice structured log messages, supports verbose, JSON serialized log messages, ... They also claimed that `zap` provides the best performance compare with other log packages (https://github.com/uber-go/zap#performance). 
I will open a pull request for this after #33 is merged.

**Comment by Liamsi** [comment]
Never heard about zap before (also suprised that uber has so many golang libs opensourced).
It looks a little verbose while coding but the performance looks very impressive. Good choice.

**Comment by c633** [comment]
Use `zap.SugaredLogger` for now. See its APIs document here: https://github.com/uber-go/zap/blob/master/README.md#quick-start

```
logger.Infow(message, 
             key, value, 
             ...)
```
outputs:

`{"msg":message,"key":value}`

and 
```
logger.Infof("sprintf formatted %s", "string")
```
outputs:
 `"msg: sprintf formatted string"`
